/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import SaudeCerteira.SaudeWallet;
import SaudeCerteira.User;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jlfernandes
 */
public class JanelaRegister extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaRegister.class.getName());

    /**
     * Creates new form JanelaRegister
     */
    public JanelaRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        txtUtente = new javax.swing.JTextField();
        txtNaturalidade = new javax.swing.JTextField();
        txtNacionalidade = new javax.swing.JTextField();
        txtCC = new javax.swing.JTextField();
        txtNIF = new javax.swing.JTextField();
        txtNISS = new javax.swing.JTextField();
        txtUnidadeSaude = new javax.swing.JTextField();
        txtSexo = new javax.swing.JTextField();
        txtMorada = new javax.swing.JTextField();
        RegistarButton = new javax.swing.JButton();
        txtConfirmPassword = new javax.swing.JTextField();
        txtTelemovel = new javax.swing.JTextField();
        medico = new javax.swing.JCheckBox();
        RegistarButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setFont(new java.awt.Font("ITF Devanagari", 3, 48)); // NOI18N
        jLabel3.setText("Saúde Certeira");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        txtNome.setText("Nome:");
        txtNome.addActionListener(this::txtNomeActionPerformed);

        txtPassword.setText("Pass:");
        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        txtDataNascimento.setText("Data de Nascimento:");
        txtDataNascimento.addActionListener(this::txtDataNascimentoActionPerformed);

        txtUtente.setText("Nº Utente:");
        txtUtente.addActionListener(this::txtUtenteActionPerformed);

        txtNaturalidade.setText("Naturalidade:");
        txtNaturalidade.addActionListener(this::txtNaturalidadeActionPerformed);

        txtNacionalidade.setText("País de Nacionalidade:");
        txtNacionalidade.addActionListener(this::txtNacionalidadeActionPerformed);

        txtCC.setText("Nº Identificação:");
        txtCC.addActionListener(this::txtCCActionPerformed);

        txtNIF.setText("NIF:");
        txtNIF.addActionListener(this::txtNIFActionPerformed);

        txtNISS.setText("NISS:");
        txtNISS.addActionListener(this::txtNISSActionPerformed);

        txtUnidadeSaude.setText("Unidade de Saúde:");
        txtUnidadeSaude.addActionListener(this::txtUnidadeSaudeActionPerformed);

        txtSexo.setText("Sexo:");
        txtSexo.addActionListener(this::txtSexoActionPerformed);

        txtMorada.setText("Morada:");
        txtMorada.addActionListener(this::txtMoradaActionPerformed);

        RegistarButton.setBackground(new java.awt.Color(204, 255, 255));
        RegistarButton.setFont(new java.awt.Font("Hiragino Sans", 3, 18)); // NOI18N
        RegistarButton.setText("Registar");
        RegistarButton.addActionListener(this::RegistarButtonActionPerformed);

        txtConfirmPassword.setText("Confirmar Pass:");
        txtConfirmPassword.addActionListener(this::txtConfirmPasswordActionPerformed);

        txtTelemovel.setText("Telemóvel:");
        txtTelemovel.addActionListener(this::txtTelemovelActionPerformed);

        medico.setBackground(new java.awt.Color(204, 255, 255));
        medico.setText("Médico");

        RegistarButton1.setBackground(new java.awt.Color(204, 255, 255));
        RegistarButton1.setFont(new java.awt.Font("Hiragino Sans", 3, 18)); // NOI18N
        RegistarButton1.setText("Login");
        RegistarButton1.addActionListener(this::RegistarButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUtente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNaturalidade)
                            .addComponent(txtNacionalidade)
                            .addComponent(txtCC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNIF)
                            .addComponent(txtNISS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUnidadeSaude)
                            .addComponent(txtSexo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelemovel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConfirmPassword))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(medico, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))
                    .addComponent(txtMorada))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(RegistarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(RegistarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUtente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNISS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnidadeSaude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medico, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistarButton)
                    .addComponent(RegistarButton1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void txtUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUtenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUtenteActionPerformed

    private void txtNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNaturalidadeActionPerformed

    private void txtNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalidadeActionPerformed

    private void txtCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCActionPerformed

    private void txtNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIFActionPerformed

    private void txtNISSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNISSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNISSActionPerformed

    private void txtUnidadeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadeSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadeSaudeActionPerformed

    private void txtSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSexoActionPerformed

    private void txtMoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoradaActionPerformed

    private void RegistarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarButtonActionPerformed
        try {
        // 1. Recolher dados da GUI
        String name = txtNome.getText().trim();
        String pass = txtPassword.getText();
        String confirmPass = txtConfirmPassword.getText();

        // Validação de passwords
        if (!pass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(this, "As passwords não coincidem!", "Erro de Registo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Recolha dos restantes campos
        String dataNasc = txtDataNascimento.getText();
        String cc = txtCC.getText();
        String utente = txtUtente.getText();
        String sexo = txtSexo.getText();
        String nacionalidade = txtNacionalidade.getText();
        String naturalidade = txtNaturalidade.getText();
        String morada = txtMorada.getText();
        String niss = txtNISS.getText();
        String telemovel = txtTelemovel.getText();
        boolean isMedico = medico.isSelected();
        String unidade = txtUnidadeSaude.getText();

        // 2. Validação de campos obrigatórios
        if (name.isEmpty() || pass.isEmpty() || confirmPass.isEmpty()
                || dataNasc.isEmpty() || cc.isEmpty() || utente.isEmpty() 
                || sexo.isEmpty() || nacionalidade.isEmpty() || naturalidade.isEmpty()
                || morada.isEmpty() || niss.isEmpty() || telemovel.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!");
            return;
        }

        // 3. Execução do Registo e Criação de Carteira
        RegistarButton.setEnabled(false); // Evita cliques múltiplos
        
        new Thread(() -> {
            try {
                // ALTERAÇÃO AQUI: Usamos SaudeWallet.create em vez de User.register
                // Isto cria o Utilizador (chaves RSA/AES) E a Carteira (ficheiro .wlt)
                SaudeWallet.create(name, pass, dataNasc, cc, utente, sexo, 
                                 nacionalidade, naturalidade, morada, 
                                 niss, telemovel, isMedico, unidade);
                
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, "Utilizador e Carteira de " + name + " criados com sucesso!");
                    RegistarButton.setEnabled(true);
                    
                         });
                
            } catch (Exception ex) {
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, "Erro no Registo/Carteira: " + ex.getMessage(), 
                            "Erro", JOptionPane.ERROR_MESSAGE);
                    RegistarButton.setEnabled(true);
                });
            }
        }).start();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao processar formulário: " + e.getMessage());
    }

    }//GEN-LAST:event_RegistarButtonActionPerformed

    private void txtConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmPasswordActionPerformed

    private void txtTelemovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelemovelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelemovelActionPerformed

    private void RegistarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarButton1ActionPerformed
         JanelaLogin Login =  new JanelaLogin();
         Login.setVisible(true);
         Login.setLocationRelativeTo(null);
         
         this.dispose();

    }//GEN-LAST:event_RegistarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JanelaRegister().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegistarButton;
    private javax.swing.JButton RegistarButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox medico;
    private javax.swing.JTextField txtCC;
    private javax.swing.JTextField txtConfirmPassword;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtMorada;
    private javax.swing.JTextField txtNIF;
    private javax.swing.JTextField txtNISS;
    private javax.swing.JTextField txtNacionalidade;
    private javax.swing.JTextField txtNaturalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtTelemovel;
    private javax.swing.JTextField txtUnidadeSaude;
    private javax.swing.JTextField txtUtente;
    // End of variables declaration//GEN-END:variables
}
