/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import SaudeCerteira.User;
import javax.swing.JOptionPane;

/**
 *
 * @author jlfernandes
 */
public class JanelaRegister extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanelaRegister.class.getName());

    /**
     * Creates new form JanelaRegister
     */
    public JanelaRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UtilizadorField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JTextField();
        RegistarButton = new javax.swing.JButton();
        TxtDataNascimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtIdentificacaoCivil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CheckMedico = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        TxtSexo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TxtPais = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtNumeroUtente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtNISS = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TxtMorada = new javax.swing.JTextField();
        TxtNaturalidade = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtUnidadeSaude = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtTelemovel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Hiragino Sans", 0, 36)); // NOI18N
        jLabel3.setText("Saúde Certeira");

        jLabel1.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel1.setText("Nome");

        UtilizadorField.addActionListener(this::UtilizadorFieldActionPerformed);

        jLabel2.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel2.setText("Password");

        RegistarButton.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        RegistarButton.setText("Registar");
        RegistarButton.addActionListener(this::RegistarButtonActionPerformed);

        jLabel4.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel4.setText("Sexo");

        jLabel6.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel6.setText("Identificação Civil");

        CheckMedico.setText("Médico");

        jLabel7.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel7.setText("Data Nascimento");

        jLabel8.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel8.setText("Naturalidade");

        jLabel9.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel9.setText("Numero Utente");

        jLabel10.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel10.setText("País Nacionalidade");

        TxtNISS.addActionListener(this::TxtNISSActionPerformed);

        jLabel11.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel11.setText("NISS");

        jLabel12.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel12.setText("Telemóvel");

        TxtNaturalidade.addActionListener(this::TxtNaturalidadeActionPerformed);

        jLabel13.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel13.setText("Morada");

        jLabel14.setFont(new java.awt.Font("Hiragino Sans", 0, 24)); // NOI18N
        jLabel14.setText("Unidade Saude");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(RegistarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UtilizadorField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(TxtNumeroUtente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(TxtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(TxtMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CheckMedico)
                                .addComponent(jLabel12)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(TxtNISS, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(TxtIdentificacaoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(TxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(TxtUnidadeSaude, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(261, Short.MAX_VALUE)
                    .addComponent(TxtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(123, 123, 123)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel13)
                    .addContainerGap(412, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(TxtTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(362, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(UtilizadorField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIdentificacaoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNumeroUtente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNISS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtUnidadeSaude, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(CheckMedico)
                .addGap(14, 14, 14)
                .addComponent(RegistarButton)
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(439, Short.MAX_VALUE)
                    .addComponent(TxtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(318, 318, 318)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(484, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(269, 269, 269)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(608, Short.MAX_VALUE)
                    .addComponent(TxtTelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(149, 149, 149)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarButtonActionPerformed
        try {
            //Criar Utilizador
            String name = UtilizadorField.getText();
            String password = PasswordField.getText();
            String dataNascimento = TxtDataNascimento.getText();
            String identificacaoCC = TxtIdentificacaoCivil.getText();
            String numeroUtente = TxtNumeroUtente.getText();
            String sexo = TxtSexo.getText();
            String paisNacionalidade = TxtPais.getText();
            String naturalidade = TxtNaturalidade.getText();
            String morada = TxtMorada.getText();
            String NISS = TxtNISS.getText();
            String telemovel = TxtTelemovel.getText();
            Boolean medico = CheckMedico.isSelected();
            String unidadeSaude = TxtUnidadeSaude.getText();
            User user = User.register(name, password, dataNascimento, identificacaoCC, numeroUtente, sexo, paisNacionalidade, naturalidade, morada, NISS, telemovel, medico, unidadeSaude);
            SaudeCerteira.SaudeWallet.create(user);
            JOptionPane.showMessageDialog(this, "wallet created :" + name, "Create user", JOptionPane.WARNING_MESSAGE);

            JanelaLogin janela = new JanelaLogin();
            janela.setLocationRelativeTo(null);
            janela.setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            System.getLogger(NodeP2PGui.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_RegistarButtonActionPerformed

    private void UtilizadorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtilizadorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UtilizadorFieldActionPerformed

    private void TxtNISSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNISSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNISSActionPerformed

    private void TxtNaturalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNaturalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNaturalidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JanelaRegister().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckMedico;
    private javax.swing.JTextField PasswordField;
    private javax.swing.JButton RegistarButton;
    private javax.swing.JTextField TxtDataNascimento;
    private javax.swing.JTextField TxtIdentificacaoCivil;
    private javax.swing.JTextField TxtMorada;
    private javax.swing.JTextField TxtNISS;
    private javax.swing.JTextField TxtNaturalidade;
    private javax.swing.JTextField TxtNumeroUtente;
    private javax.swing.JTextField TxtPais;
    private javax.swing.JTextField TxtSexo;
    private javax.swing.JTextField TxtTelemovel;
    private javax.swing.JTextField TxtUnidadeSaude;
    private javax.swing.JTextField UtilizadorField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
