/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import SaudeCerteira.SaudeTransaction;
import SaudeCerteira.SaudeWallet;
import SaudeCerteira.User;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.security.PrivateKey;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import utils.GuiUtils;
import utils.RMI;
import utils.Serializer;
import utils.Utils;

/**
 *
 * @author angelacsebastiao
 */
public class MainGUI extends javax.swing.JFrame  implements Nodelistener, MinerListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainGUI.class.getName());
    private PerfilUser janelaPerfil;
    private SaudeCerteira.User utilizadorLogado;
    
    RemoteNodeObject myremoteObject;
    String nomeUser = "Master";
    
    // Variável para guardar o bloco que estamos a tentar minerar
    core.Block blocoCandidato = null;

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
       initComponents();
       txtServerListeningObjectName.setText(RemoteNodeObject.REMOTE_OBJECT_NAME);
       setRandomPosition();
       // Inicia servidor automaticamente para facilitar
       btStartServerActionPerformed(null);
    }
    
    public MainGUI(SaudeCerteira.User user) {
        initComponents();
        txtServerListeningObjectName.setText(RemoteNodeObject.REMOTE_OBJECT_NAME);
        setRandomPosition();
        
        this.utilizadorLogado = user;
        this.nomeUser = user.getUserName();
        this.janelaPerfil = new PerfilUser(user, this);
        
        // --- CARREGAR SNS24 (Minhas Receitas) ---
        carregarInventarioSNS24();
    }

    private void carregarInventarioSNS24() {
        if (this.utilizadorLogado != null) {
            try {
                SaudeWallet wallet = SaudeWallet.load(this.utilizadorLogado.getUserName());
                // Usa a chave privada para desencriptar o histórico
                String relatorio = wallet.getInventarioDescodificado(this.utilizadorLogado.getPrivateKey());
                jTextArea1.setText(relatorio);
            } catch (Exception e) {
                jTextArea1.setText("Erro ao carregar receitas: " + e.getMessage());
            }
        }
    }
    
     private void setRandomPosition() {
        this.setSize(776, 520);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Random r = new Random();
        int x = r.nextInt(screenSize.width - this.getWidth());
        int y = r.nextInt(screenSize.height - this.getHeight());
        setLocation(x, y);
        
        txtServerListeningPort.setText("1000" + r.nextInt(10));
        
        // Auto-start
        btStartServerActionPerformed(null);
        btConnectActionPerformed(null);
        loadMedicinesToGUI();
    }

     private void loadMedicinesToGUI() {
        try {
            String path = "src/multimedia/medicines_output_medicines_en - Medicine.csv";
            List<String> medicines = Utils.getMedicineNames(path);
            String[] medArray = medicines.toArray(new String[0]);
            if (Medicamentos != null) {
                Medicamentos.setModel(new DefaultComboBoxModel<>(medArray));
            }
        } catch (Exception e) {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        tpMain = new javax.swing.JTabbedPane();
        pnServer = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtServerLog = new javax.swing.JTextPane();
        txtServerListeningObjectName = new javax.swing.JTextField();
        btStartServer = new javax.swing.JButton();
        txtServerListeningPort = new javax.swing.JTextField();
        imgServerRunning = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pnConnect = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNetwork = new javax.swing.JTextArea();
        txtNodeAddress = new javax.swing.JTextField();
        btConnect = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnMine = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        spZeros = new javax.swing.JSpinner();
        btStartMinig = new javax.swing.JButton();
        imgMiner = new javax.swing.JLabel();
        imgWinner = new javax.swing.JLabel();
        txtNonce = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMinerMessage = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        pnCriarReceitas = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        btAddTransaction = new javax.swing.JButton();
        Medicamentos = new javax.swing.JComboBox<>();
        QuantidadeMed = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomeUtente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLstTransactions = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        pnVerReceitas = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(560, 427));
        setResizable(false);

        jPanel11.setBackground(new java.awt.Color(0, 204, 204));

        jPanel12.setLayout(new java.awt.BorderLayout(10, 10));

        txtServerLog.setBackground(new java.awt.Color(204, 255, 255));
        txtServerLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Log Server"));
        txtServerLog.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(txtServerLog);

        txtServerListeningObjectName.setEditable(false);
        txtServerListeningObjectName.setBackground(new java.awt.Color(226, 247, 255));
        txtServerListeningObjectName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtServerListeningObjectName.setText("remoteP2P");
        txtServerListeningObjectName.setBorder(javax.swing.BorderFactory.createTitledBorder("ObjectName"));

        btStartServer.setBackground(new java.awt.Color(226, 247, 255));
        btStartServer.setFont(new java.awt.Font("Hiragino Sans", 1, 13)); // NOI18N
        btStartServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/startServer.png"))); // NOI18N
        btStartServer.setText("Start");
        btStartServer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartServerActionPerformed(evt);
            }
        });

        txtServerListeningPort.setBackground(new java.awt.Color(226, 247, 255));
        txtServerListeningPort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtServerListeningPort.setText("10010");
        txtServerListeningPort.setBorder(javax.swing.BorderFactory.createTitledBorder("Port Number"));
        txtServerListeningPort.setPreferredSize(new java.awt.Dimension(200, 36));
        txtServerListeningPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServerListeningPortActionPerformed(evt);
            }
        });

        imgServerRunning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/loading_green.gif"))); // NOI18N
        imgServerRunning.setEnabled(false);

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton3.setText("Ver Perfil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(imgServerRunning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btStartServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtServerListeningObjectName)
                                    .addComponent(txtServerListeningPort, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)
                                .addGap(16, 16, 16)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 31, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 128, Short.MAX_VALUE)))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(txtServerListeningObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtServerListeningPort, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(imgServerRunning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addGap(0, 95, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 346, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnServerLayout = new javax.swing.GroupLayout(pnServer);
        pnServer.setLayout(pnServerLayout);
        pnServerLayout.setHorizontalGroup(
            pnServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnServerLayout.setVerticalGroup(
            pnServerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tpMain.addTab("Servidor", pnServer);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setAutoscrolls(true);

        txtNetwork.setEditable(false);
        txtNetwork.setBackground(new java.awt.Color(204, 255, 255));
        txtNetwork.setColumns(20);
        txtNetwork.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtNetwork.setRows(5);
        jScrollPane2.setViewportView(txtNetwork);

        txtNodeAddress.setBackground(new java.awt.Color(226, 247, 255));
        txtNodeAddress.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtNodeAddress.setText("//ip a conectar");
        txtNodeAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Remote Object Address"));
        txtNodeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNodeAddressActionPerformed(evt);
            }
        });
        txtNodeAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNodeAddressKeyPressed(evt);
            }
        });

        btConnect.setBackground(new java.awt.Color(226, 247, 255));
        btConnect.setFont(new java.awt.Font("Hiragino Sans", 1, 13)); // NOI18N
        btConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/startClient.jpg"))); // NOI18N
        btConnect.setText("Conectar");
        btConnect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btConnect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConnectActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton2.setText("Ver Perfil");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(txtNodeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btConnect)
                    .addComponent(txtNodeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout pnConnectLayout = new javax.swing.GroupLayout(pnConnect);
        pnConnect.setLayout(pnConnectLayout);
        pnConnectLayout.setHorizontalGroup(
            pnConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnConnectLayout.setVerticalGroup(
            pnConnectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tpMain.addTab("Conectar", pnConnect);

        jPanel9.setBackground(new java.awt.Color(0, 204, 204));

        spZeros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        spZeros.setModel(new javax.swing.SpinnerNumberModel(3, 2, null, 1));
        spZeros.setBorder(javax.swing.BorderFactory.createTitledBorder("Dificulty"));

        btStartMinig.setBackground(new java.awt.Color(204, 255, 255));
        btStartMinig.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btStartMinig.setText("Start Mining");
        btStartMinig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btStartMinig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btStartMinig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartMinigActionPerformed(evt);
            }
        });

        imgMiner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/working.gif"))); // NOI18N

        imgWinner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/winner.gif"))); // NOI18N

        txtNonce.setBackground(new java.awt.Color(226, 247, 255));
        txtNonce.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNonce.setText("0");
        txtNonce.setBorder(javax.swing.BorderFactory.createTitledBorder("Nonce"));
        txtNonce.setPreferredSize(new java.awt.Dimension(200, 36));
        txtNonce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNonceActionPerformed(evt);
            }
        });

        txtMinerMessage.setBackground(new java.awt.Color(204, 255, 255));
        txtMinerMessage.setColumns(20);
        txtMinerMessage.setRows(5);
        jScrollPane4.setViewportView(txtMinerMessage);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setText("Ver Perfil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtNonce, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(spZeros, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btStartMinig, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgMiner, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)))
                .addGap(45, 45, 45))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNonce, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spZeros, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btStartMinig, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(imgWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(imgMiner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnMineLayout = new javax.swing.GroupLayout(pnMine);
        pnMine.setLayout(pnMineLayout);
        pnMineLayout.setHorizontalGroup(
            pnMineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnMineLayout.setVerticalGroup(
            pnMineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tpMain.addTab("Minerar", pnMine);

        jPanel10.setBackground(new java.awt.Color(0, 204, 204));

        btAddTransaction.setBackground(new java.awt.Color(204, 255, 255));
        btAddTransaction.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btAddTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/transaction.png"))); // NOI18N
        btAddTransaction.setText("Nova Receita");
        btAddTransaction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAddTransaction.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btAddTransaction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddTransactionActionPerformed(evt);
            }
        });

        Medicamentos.setBackground(new java.awt.Color(226, 247, 255));
        Medicamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Medicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicamentosActionPerformed(evt);
            }
        });

        QuantidadeMed.setBackground(new java.awt.Color(226, 247, 255));
        QuantidadeMed.setMinimumSize(new java.awt.Dimension(90, 20));
        QuantidadeMed.setPreferredSize(new java.awt.Dimension(90, 20));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Para quem?");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Quantidade:");

        NomeUtente.setBackground(new java.awt.Color(226, 247, 255));
        NomeUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeUtenteActionPerformed(evt);
            }
        });

        txtLstTransactions.setBackground(new java.awt.Color(226, 247, 255));
        txtLstTransactions.setColumns(20);
        txtLstTransactions.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtLstTransactions.setRows(2);
        txtLstTransactions.setPreferredSize(new java.awt.Dimension(939, 89));
        txtLstTransactions.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(txtLstTransactions);

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton4.setText("Ver Perfil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Medicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel10Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(QuantidadeMed, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NomeUtente))))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jButton4))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btAddTransaction))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Medicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(QuantidadeMed, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomeUtente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(btAddTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout pnCriarReceitasLayout = new javax.swing.GroupLayout(pnCriarReceitas);
        pnCriarReceitas.setLayout(pnCriarReceitasLayout);
        pnCriarReceitasLayout.setHorizontalGroup(
            pnCriarReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnCriarReceitasLayout.setVerticalGroup(
            pnCriarReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tpMain.addTab("Criar Receitas", pnCriarReceitas);

        jPanel13.setBackground(new java.awt.Color(0, 204, 204));

        jTextArea1.setBackground(new java.awt.Color(226, 247, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout pnVerReceitasLayout = new javax.swing.GroupLayout(pnVerReceitas);
        pnVerReceitas.setLayout(pnVerReceitasLayout);
        pnVerReceitasLayout.setHorizontalGroup(
            pnVerReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnVerReceitasLayout.setVerticalGroup(
            pnVerReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tpMain.addTab("Minhas Receitas", pnVerReceitas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpMain, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>                        

    private void txtServerListeningPortActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void btStartServerActionPerformed(java.awt.event.ActionEvent evt) {                                              
        try {
            // [FIX] FORCE RMI TO USE THE REAL IP
            String realIp = RemoteNodeObject.getRealIp();
            System.setProperty("java.rmi.server.hostname", realIp);
            System.out.println("RMI Hostname forced to: " + realIp);

            int port = Integer.parseInt(txtServerListeningPort.getText());
            String name = RemoteNodeObject.REMOTE_OBJECT_NAME;

            myremoteObject = new RemoteNodeObject(port, this);
            RMI.startRemoteObject(myremoteObject, port, name);

            this.setTitle(RMI.getRemoteName(port, name));
            this.txtNodeAddress.setText(RMI.getRemoteName(port, name));

            if(myremoteObject.miner != null) myremoteObject.miner.addListener(this);

        } catch (Exception ex) {
            onException(ex, "Starting server");
        }
    }                                             

    private void txtNodeAddressActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txtNodeAddressKeyPressed(java.awt.event.KeyEvent evt) {                                          
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        btConnectActionPerformed(null);
    }                                         

    private void btConnectActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try {
            String address = txtNodeAddress.getText();
            RemoteNodeInterface node = (RemoteNodeInterface) RMI.getRemote(address);
            myremoteObject.addNode(node);
        } catch (Exception ex) {
            onException(ex, "connect");
        }

    }                                         

    private void btStartMinigActionPerformed(java.awt.event.ActionEvent evt) {                                             
         try {
            // 1. Carregar Blockchain Local
            core.BlockChain bc = core.BlockChain.load(core.BlockChain.FILE_PATH + "blockchain.bch");
            
            int nextID = (bc != null && bc.getLastBlock() != null) ? bc.getLastBlock().getID() + 1 : 1;
            byte[] prevHash = (bc != null && bc.getLastBlock() != null) ? bc.getLastBlock().getCurrentHash() : new byte[32];

            // 2. Filtrar Transações e verificar duplicados na Blockchain
            List<String> pendentes = myremoteObject.getTransactions();
            List<SaudeCerteira.SaudeTransaction> txsReais = new ArrayList<>();
            List<String> lixoParaRemover = new ArrayList<>();

            for (String s : pendentes) {
                try {
                    SaudeCerteira.SaudeTransaction t = (SaudeCerteira.SaudeTransaction) utils.Serializer.byteArrayToObject(java.util.Base64.getDecoder().decode(s));
                    if (bc != null && bc.existsTransaction(t.getSignature())) {
                        lixoParaRemover.add(s); 
                        continue; 
                    }
                    txsReais.add(t);
                } catch (Exception e) {
                    lixoParaRemover.add(s);
                }
            }

            if (txsReais.isEmpty()) {
                txtLstTransactions.setText("");
                JOptionPane.showMessageDialog(this, "Sem transações válidas para minerar.");
                return;
            }

            // 3. Criar Bloco
            int dif = (int) spZeros.getValue();
            this.blocoCandidato = new core.Block(nextID, prevHash, dif, txsReais);

            // 4. Iniciar Mineração
            byte[] headerBytes = this.blocoCandidato.getHeaderData();
            String headerParaMinar = java.util.Base64.getEncoder().encodeToString(headerBytes);
            
            new Thread(() -> {
                try {
                    myremoteObject.mine(headerParaMinar, dif);
                    for (RemoteNodeInterface node : myremoteObject.getNetwork()) {
                        try { node.mine(headerParaMinar, dif); } catch (Exception e) {}
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }).start();

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }                                            

    private void btAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        String patientName = NomeUtente.getText().trim();
        String selectedDrug = (String) Medicamentos.getSelectedItem();
        int quantidade;
        try {
            quantidade = Integer.parseInt(QuantidadeMed.getText());
        } catch (NumberFormatException e) {
            quantidade = 1;
        }

        if (patientName.isEmpty() || selectedDrug == null) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return;
        }

        try {
            // 1. Procurar o utilizador na rede P2P (para obter a chave publica)
            User pacienteEncontrado = myremoteObject.searchUser(patientName);
            if (pacienteEncontrado == null) {
                JOptionPane.showMessageDialog(this, "Utente não encontrado na rede.");
                return;
            }
            
            // 2. Guardar a chave localmente
            utils.SecurityUtils.saveKey(pacienteEncontrado.getPublicKey(), "data_user/" + patientName);
             try (java.io.ObjectOutputStream out = new java.io.ObjectOutputStream(new java.io.FileOutputStream("data_user/" + patientName + ".user"))) {
                out.writeObject(pacienteEncontrado);
            }

            // 3. Criar a Transação (Construtor já faz a encriptação)
            SaudeTransaction trans = new SaudeTransaction(nomeUser, patientName, quantidade, selectedDrug);

            // 4. Assinar
            User userAtual = User.login(nomeUser);
            if (userAtual.isMedico()){
                if (userAtual.getPrivateKey() == null) {
                    String pass = JOptionPane.showInputDialog(this, "Password para assinar:");
                    if (pass == null) return;
                    userAtual = User.login(nomeUser, pass);
                }
                
                trans.sign(userAtual.getPrivateKey());

                // 5. Enviar
                byte[] transBytes = utils.Serializer.objectToByteArray(trans);
                String transString = Base64.getEncoder().encodeToString(transBytes);

                if (myremoteObject != null) {
                    myremoteObject.addTransaction(transString);
                    JOptionPane.showMessageDialog(this, "Receita enviada!");
                }
            } else {
                 JOptionPane.showMessageDialog(this, "Apenas médicos podem prescrever.");
            }
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
            ex.printStackTrace();
        }
    }                                                

    private void MedicamentosActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void NomeUtenteActionPerformed(java.awt.event.ActionEvent evt) {                                           
          try {
            String nomeProcurar = NomeUtente.getText().trim();
            if (nomeProcurar.isEmpty()) return;
            User encontrado = myremoteObject.searchUser(nomeProcurar);
            if (encontrado != null) {
                JOptionPane.showMessageDialog(this, "Utilizador encontrado: " + encontrado.getUserName());
            } else {
                JOptionPane.showMessageDialog(this, "Utilizador não encontrado.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro na pesquisa: " + ex.getMessage());
        }
    }                                          

    
  
    
    private void txtNonceActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        PerfilUser perfil = new PerfilUser(this.utilizadorLogado, this);
        perfil.setVisible(true);
        this.setVisible(false);
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        PerfilUser perfil = new PerfilUser(this.utilizadorLogado, this);
        perfil.setVisible(true);
        this.setVisible(false);     
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        PerfilUser perfil = new PerfilUser(this.utilizadorLogado, this);
        perfil.setVisible(true);
        this.setVisible(false);     
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        PerfilUser perfil = new PerfilUser(this.utilizadorLogado, this);
        perfil.setVisible(true);
        this.setVisible(false);     
    }                                        

    
    
    @Override
    public void onStart(String message) {
        imgServerRunning.setEnabled(true);
        btStartServer.setEnabled(false);
        GuiUtils.addText(txtServerLog, "Start server", message);
    }

    @Override
    public void onException(Exception e, String title) {
        JOptionPane.showMessageDialog(this, e.getMessage(), title, JOptionPane.WARNING_MESSAGE);
    }

    @Override
    public void onConect(String address) {
        try {
            List<RemoteNodeInterface> net = myremoteObject.getNetwork();
            String txt = "";
            for (RemoteNodeInterface iremoteP2P : net) {
                txt += iremoteP2P.getAdress() + "\n";
            }
            txtNetwork.setText(txt);
            tpMain.setSelectedComponent(pnConnect);
            onTransaction("Syncronize to " + address);
        } catch (RemoteException ex) {
            onException(ex, "On conect");
        }

    }
    
    @Override
    public void onTransaction(String data) {
        SwingUtilities.invokeLater(() -> {
        try {
            if (data.equals("BlockReceived")) {
                txtLstTransactions.setText("");
                return;
            }
            // Tenta descodificar como Base64 (Transação Real)
            try {
                byte[] bytes = Base64.getDecoder().decode(data);
                SaudeTransaction tx = (SaudeTransaction) Serializer.byteArrayToObject(bytes);
                txtLstTransactions.append(tx.toString() + "\n");
            } catch (IllegalArgumentException e) {
                // Se falhar Base64, é texto simples (Log)
                txtLstTransactions.append(data + "\n");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    });

    }

    @Override
    public void onStartMining(String message, int dificulty) {
        SwingUtilities.invokeLater(() -> {
            imgMiner.setVisible(true);
            imgWinner.setVisible(false);
            txtMinerMessage.setText(message);
        });

    }

    @Override
    public void onStopMining(int nonce) {
        SwingUtilities.invokeLater(() -> {
            try {
                imgMiner.setVisible(false);
                btStartMinig.setEnabled(true);
                txtNonce.setText("" + nonce);
                txtMinerMessage.setText(myremoteObject.getHash());

            } catch (Exception ex) {
            }
        });

    }

    @Override
    public void onNonceFound(int nonce) {
        SwingUtilities.invokeLater(() -> {
            try {
                imgWinner.setVisible(true);
                
                // 1. Parar mineração (Local e Rede)
                myremoteObject.stopMining(nonce);
                List<RemoteNodeInterface> rede = myremoteObject.getNetwork();
                for (RemoteNodeInterface node : rede) {
                    try { node.stopMining(nonce); } catch (Exception e) {}
                }

                // 2. Finalizar Bloco e Propagar
                if (this.blocoCandidato != null) {
                    this.blocoCandidato.setNonce(nonce);
                    byte[] blockBytes = utils.Serializer.objectToByteArray(this.blocoCandidato);
                    
                    myremoteObject.propagateBlock(blockBytes);
                    
                    // Limpar estado local
                    this.blocoCandidato = null;
                    txtLstTransactions.setText("");
                    JOptionPane.showMessageDialog(this, "Bloco Minado e Propagado!");
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        });
    }


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainGUI().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> Medicamentos;
    private javax.swing.JTextField NomeUtente;
    private javax.swing.JTextField QuantidadeMed;
    private javax.swing.JButton btAddTransaction;
    private javax.swing.JButton btConnect;
    private javax.swing.JButton btStartMinig;
    private javax.swing.JButton btStartServer;
    private javax.swing.JLabel imgMiner;
    private javax.swing.JLabel imgServerRunning;
    private javax.swing.JLabel imgWinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnConnect;
    private javax.swing.JPanel pnCriarReceitas;
    private javax.swing.JPanel pnMine;
    private javax.swing.JPanel pnServer;
    private javax.swing.JPanel pnVerReceitas;
    private javax.swing.JSpinner spZeros;
    private javax.swing.JTabbedPane tpMain;
    private javax.swing.JTextArea txtLstTransactions;
    private javax.swing.JTextArea txtMinerMessage;
    private javax.swing.JTextArea txtNetwork;
    private javax.swing.JTextField txtNodeAddress;
    private javax.swing.JTextField txtNonce;
    private javax.swing.JTextField txtServerListeningObjectName;
    private javax.swing.JTextField txtServerListeningPort;
    private javax.swing.JTextPane txtServerLog;
    // End of variables declaration                   
}