//::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: 
//::                                                                         ::
//::     Antonio Manuel Rodrigues Manso                                      ::
//::                                                                         ::
//::     I N S T I T U T O    P O L I T E C N I C O   D E   T O M A R        ::
//::     Escola Superior de Tecnologia de Tomar                              ::
//::     e-mail: manso@ipt.pt                                                ::
//::     url   : http://orion.ipt.pt/~manso                                  ::
//::                                                                         ::
//::     This software was build with the purpose of investigate and         ::
//::     learning.                                                           ::
//::                                                                         ::
//::                                                               (c)2015   ::
//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
 //////////////////////////////////////////////////////////////////////////////
package GUI;

import SaudeCerteira.SaudeTransaction;
import SaudeCerteira.SaudeWallet;
import SaudeCerteira.User;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.security.PrivateKey;
import java.util.Base64;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import utils.GuiUtils;
import utils.RMI;
import utils.SecurityUtils;
import utils.Serializer;
import utils.Utils;

/**
 *
 * @author zulu
 */
public class NodeP2PGui extends javax.swing.JFrame implements Nodelistener, MinerListener {

    RemoteNodeObject myremoteObject;
    String nomeUser = "master123";

    /**
     * Creates new form MessengerGUI
     */
    public NodeP2PGui() {
        initComponents();
        txtServerListeningObjectName.setText(RemoteNodeObject.REMOTE_OBJECT_NAME);
        setRandomPosition();
        myremoteObject.miner.addListener(this);

    }

    private void setRandomPosition() {
        //:::: Mover a janela para uma posição aleatório
        this.setSize(350, 450);
        // Obter a resolução do ecrã
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Gerar posição aleatória garantindo que a janela cabe no ecrã
        Random r = new Random();
        int x = r.nextInt(screenSize.width - this.getWidth());
        int y = r.nextInt(screenSize.height - this.getHeight());
        // Colocar a janela na posição aleatória
        setLocation(x, y);
        txtServerListeningPort.setText("1000" + r.nextInt(10));
        btStartServerActionPerformed(null);
        btConnectActionPerformed(null);
        //btAddTransactionActionPerformed(null);
        loadMedicinesToGUI();
    }

    private void loadMedicinesToGUI() {
        // 1. Define the path to your CSV file
        // Adjust "src/multimedia/..." if your folder structure is different
        String path = "src/multimedia/medicines_output_medicines_en - Medicine.csv";
        
        // 2. Get the list of names
        List<String> medicines = Utils.getMedicineNames(path);
        
        // 3. Convert to Array for the ComboBox
        String[] medArray = medicines.toArray(new String[0]);
        
        // 4. Set the model to the ComboBox
        // Assuming you named your component 'cmbMedicamentos' in the GUI Builder
        // If you didn't create it yet, I check for null to avoid crash
        if (Medicamentos != null) {
            Medicamentos.setModel(new DefaultComboBoxModel<>(medArray));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        folderUtils1 = new utils.FolderUtils();
        jPanel6 = new javax.swing.JPanel();
        txtWalletPublicKey1 = new javax.swing.JTextField();
        txtWalletPrivateKey1 = new javax.swing.JTextField();
        txtWalletAESKey1 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtWalletTransactions1 = new javax.swing.JTextArea();
        txtBalance1 = new javax.swing.JTextField();
        tpMain = new javax.swing.JTabbedPane();
        pnServer = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btStartServer = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtServerListeningPort = new javax.swing.JTextField();
        txtServerListeningObjectName = new javax.swing.JTextField();
        imgServerRunning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtServerLog = new javax.swing.JTextPane();
        pnNetwork = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNetwork = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        txtNodeAddress = new javax.swing.JTextField();
        btConnect = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        spZeros = new javax.swing.JSpinner();
        btStartMinig = new javax.swing.JButton();
        imgMiner = new javax.swing.JLabel();
        txtNonce = new javax.swing.JTextField();
        imgWinner = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMinerMessage = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnTransaction = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLstTransactions = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btAddTransaction = new javax.swing.JButton();
        Medicamentos = new javax.swing.JComboBox<>();
        QuantidadeMed = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NomeUtente = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        txtWalletPublicKey1.setEditable(false);
        txtWalletPublicKey1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtWalletPublicKey1.setBorder(javax.swing.BorderFactory.createTitledBorder("Public Key"));
        txtWalletPublicKey1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWalletPublicKey1ActionPerformed(evt);
            }
        });

        txtWalletPrivateKey1.setEditable(false);
        txtWalletPrivateKey1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtWalletPrivateKey1.setBorder(javax.swing.BorderFactory.createTitledBorder("Private Key"));

        txtWalletAESKey1.setEditable(false);
        txtWalletAESKey1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtWalletAESKey1.setBorder(javax.swing.BorderFactory.createTitledBorder("AES Key"));

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("Blockchain Transactions"));

        txtWalletTransactions1.setEditable(false);
        txtWalletTransactions1.setColumns(20);
        txtWalletTransactions1.setRows(5);
        jScrollPane6.setViewportView(txtWalletTransactions1);

        txtBalance1.setEditable(false);
        txtBalance1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        txtBalance1.setText("0.0");
        txtBalance1.setBorder(javax.swing.BorderFactory.createTitledBorder("Balance"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtWalletPrivateKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWalletPublicKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWalletAESKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(txtWalletPublicKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtWalletPrivateKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtWalletAESKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnServer.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout(10, 10));

        btStartServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/startServer.png"))); // NOI18N
        btStartServer.setText("Start");
        btStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartServerActionPerformed(evt);
            }
        });
        jPanel3.add(btStartServer, java.awt.BorderLayout.WEST);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        txtServerListeningPort.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtServerListeningPort.setText("10010");
        txtServerListeningPort.setBorder(javax.swing.BorderFactory.createTitledBorder("Port Number"));
        txtServerListeningPort.setPreferredSize(new java.awt.Dimension(200, 36));
        txtServerListeningPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServerListeningPortActionPerformed(evt);
            }
        });
        jPanel7.add(txtServerListeningPort);

        txtServerListeningObjectName.setEditable(false);
        txtServerListeningObjectName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtServerListeningObjectName.setText("remoteP2P");
        txtServerListeningObjectName.setBorder(javax.swing.BorderFactory.createTitledBorder("ObjectName"));
        jPanel7.add(txtServerListeningObjectName);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        imgServerRunning.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/loading_green.gif"))); // NOI18N
        imgServerRunning.setEnabled(false);
        jPanel3.add(imgServerRunning, java.awt.BorderLayout.EAST);

        pnServer.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        txtServerLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Log Server"));
        txtServerLog.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(txtServerLog);

        pnServer.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tpMain.addTab("Server", pnServer);

        pnNetwork.setLayout(new java.awt.BorderLayout());

        txtNetwork.setEditable(false);
        txtNetwork.setColumns(20);
        txtNetwork.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtNetwork.setRows(5);
        jScrollPane2.setViewportView(txtNetwork);

        pnNetwork.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.BorderLayout());

        txtNodeAddress.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        txtNodeAddress.setText("//10.10.208.35:10010/remoteP2P");
        txtNodeAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Remote Object Address"));
        txtNodeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNodeAddressActionPerformed(evt);
            }
        });
        txtNodeAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNodeAddressKeyPressed(evt);
            }
        });
        jPanel5.add(txtNodeAddress, java.awt.BorderLayout.CENTER);

        btConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/startClient.jpg"))); // NOI18N
        btConnect.setText("Connect");
        btConnect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btConnect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConnectActionPerformed(evt);
            }
        });
        jPanel5.add(btConnect, java.awt.BorderLayout.WEST);

        pnNetwork.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        tpMain.addTab("P2pNetwork", pnNetwork);

        spZeros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        spZeros.setModel(new javax.swing.SpinnerNumberModel(3, 2, null, 1));
        spZeros.setBorder(javax.swing.BorderFactory.createTitledBorder("Dificulty"));

        btStartMinig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/mine.png"))); // NOI18N
        btStartMinig.setText("Start Mining");
        btStartMinig.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btStartMinig.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btStartMinig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartMinigActionPerformed(evt);
            }
        });

        imgMiner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/working.gif"))); // NOI18N

        txtNonce.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNonce.setText("0");
        txtNonce.setBorder(javax.swing.BorderFactory.createTitledBorder("Nonce"));
        txtNonce.setPreferredSize(new java.awt.Dimension(200, 36));

        imgWinner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/winner.gif"))); // NOI18N

        txtMinerMessage.setColumns(20);
        txtMinerMessage.setRows(5);
        jScrollPane4.setViewportView(txtMinerMessage);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNonce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(spZeros, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btStartMinig)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(imgMiner)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(imgWinner)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btStartMinig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spZeros)
                    .addComponent(imgMiner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgWinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNonce, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpMain.addTab("Miner", jPanel4);

        jButton3.setFont(new java.awt.Font("Hiragino Sans", 0, 13)); // NOI18N
        jButton3.setText("Perfil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Hiragino Sans", 0, 13)); // NOI18N
        jButton1.setText("Criar Receita");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Hiragino Sans", 0, 13)); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(55, 55, 55)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpMain.addTab("receitas", jPanel8);

        pnTransaction.setLayout(new java.awt.BorderLayout());

        txtLstTransactions.setColumns(20);
        txtLstTransactions.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txtLstTransactions.setRows(2);
        txtLstTransactions.setPreferredSize(new java.awt.Dimension(939, 89));
        txtLstTransactions.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(txtLstTransactions);

        pnTransaction.add(jScrollPane3, java.awt.BorderLayout.LINE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btAddTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/transaction.png"))); // NOI18N
        btAddTransaction.setText("Nova Receita");
        btAddTransaction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btAddTransaction.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btAddTransaction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btAddTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddTransactionActionPerformed(evt);
            }
        });
        jPanel2.add(btAddTransaction, java.awt.BorderLayout.WEST);

        Medicamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Medicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicamentosActionPerformed(evt);
            }
        });
        jPanel2.add(Medicamentos, java.awt.BorderLayout.CENTER);

        QuantidadeMed.setMinimumSize(new java.awt.Dimension(90, 20));
        QuantidadeMed.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel2.add(QuantidadeMed, java.awt.BorderLayout.LINE_END);

        jLabel1.setText("Para quem enviar receita médica:");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_END);

        pnTransaction.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        NomeUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeUtenteActionPerformed(evt);
            }
        });
        pnTransaction.add(NomeUtente, java.awt.BorderLayout.CENTER);

        tpMain.addTab("Receitas Médicas", pnTransaction);

        getContentPane().add(tpMain, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWalletPublicKey1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWalletPublicKey1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWalletPublicKey1ActionPerformed

    private void btStartMinigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartMinigActionPerformed

        new Thread(() -> {
            try {
                String txt = Base64.getEncoder().encodeToString(txtLstTransactions.getText().getBytes());
                int dif = (int) spZeros.getValue();
                myremoteObject.mine(txt, dif);

            } catch (RemoteException ex) {
                System.getLogger(NodeP2PGui.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }).start();
    }//GEN-LAST:event_btStartMinigActionPerformed

    private void btAddTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddTransactionActionPerformed
       // 1. Get Data
    String patientName = NomeUtente.getText().trim();
    String selectedDrug = (String) Medicamentos.getSelectedItem();
    
    int quantidade;
    try {
        quantidade = Integer.parseInt(QuantidadeMed.getText());
    } catch (NumberFormatException e) {
        quantidade = 1; // Default
    }

    if (patientName.isEmpty() || selectedDrug == null) {
        JOptionPane.showMessageDialog(this, "Selecione um paciente e um medicamento.");
        return;
    }

    try {
        // 2. Criar a Transação
        // O construtor da SaudeTransaction provavelmente já faz a pesquisa P2P que implementamos
        SaudeTransaction trans = new SaudeTransaction(
            nomeUser,     // Médico
            patientName,  // Paciente
            quantidade,
            selectedDrug
        );

        // 3. Obter o User do Médico para assinar
        User userAtual = User.login(nomeUser);

        // 4. Verificar e Carregar Chave Privada
        if (userAtual.getPrivateKey() == null) {
            String pass = JOptionPane.showInputDialog(this, "Insira a password para assinar a receita:");
            
            if (pass == null) return; // Utilizador cancelou

            // RECARREGA o objeto com a password (desencripta a privada)
            userAtual = User.login(nomeUser, pass); 
        }

        // 5. ASSINAR (Agora o userAtual já tem a privada)
        PrivateKey privKey = userAtual.getPrivateKey();
        if (privKey == null) {
            throw new Exception("Falha ao carregar chave privada. Password incorreta?");
        }
        
        trans.sign(privKey);

        // 6. SERIALIZAR E ENVIAR
        // 6. SERIALIZAR E ENVIAR
        // Garanta que o Serializer está a converter o objeto 'trans' (a receita)
        byte[] transBytes = utils.Serializer.objectToByteArray(trans); 
        String transString = Base64.getEncoder().encodeToString(transBytes);

        if (myremoteObject != null) {
            myremoteObject.addTransaction(transString);
            JOptionPane.showMessageDialog(this, "Receita enviada com sucesso!");

            // Se não quer que a janela feche imediatamente, remova ou comente a linha abaixo:
            // this.dispose(); 
        }

    } catch (Exception ex) {
        // Trata erros de: Paciente não encontrado, Password errada ou erro de rede
        JOptionPane.showMessageDialog(this, "Erro no processo: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btAddTransactionActionPerformed

    private void btConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConnectActionPerformed
        try {
            String address = txtNodeAddress.getText();
            RemoteNodeInterface node = (RemoteNodeInterface) RMI.getRemote(address);
            myremoteObject.addNode(node);
        } catch (Exception ex) {
            onException(ex, "connect");
            Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConnectActionPerformed

    private void txtNodeAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNodeAddressKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            btConnectActionPerformed(null);
    }//GEN-LAST:event_txtNodeAddressKeyPressed

    private void txtNodeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNodeAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNodeAddressActionPerformed

    private void btStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartServerActionPerformed
        try {
            // ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            // [FIX] FORCE RMI TO USE THE REAL IP (Not Docker/Localhost)
            // This MUST be done before creating the RemoteNodeObject
            String realIp = RemoteNodeObject.getRealIp();
            System.setProperty("java.rmi.server.hostname", realIp);
            System.out.println("RMI Hostname forced to: " + realIp);
            // ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

            //:::::::::: Objeto remoto  :::::::::::::::
            int port = Integer.parseInt(txtServerListeningPort.getText());
            String name = RemoteNodeObject.REMOTE_OBJECT_NAME;
            
            // Now create the object (It will now use the correct IP in the Stub)
            myremoteObject = new RemoteNodeObject(port, this);
            
            RMI.startRemoteObject(myremoteObject, port, name);
            
            //:::::::: GUI  ::::::::::::::::
            this.setTitle(RMI.getRemoteName(port, name));
            this.txtNodeAddress.setText(RMI.getRemoteName(port, name));
            
            // Re-enable miner listener now that object exists
             if(myremoteObject.miner != null) myremoteObject.miner.addListener(this);
             
        } catch (Exception ex) {
            onException(ex, "Starting server");
            Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btStartServerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        CriarReceitas criarRec = new CriarReceitas();
        criarRec.setLocationRelativeTo(null);
        criarRec.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtServerListeningPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServerListeningPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServerListeningPortActionPerformed

    private void MedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicamentosActionPerformed

    private void NomeUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeUtenteActionPerformed

          try {
            // 1. Obter o nome do utilizador da TextBox
            String nomeProcurar = NomeUtente.getText().trim();

            if (nomeProcurar.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, insira um nome de utilizador.");
                return;
            }

            // 2. Chamar o método de pesquisa (que faz a busca local e P2P)
            // Nota: Assumindo que o seu objeto remoto está acessível na GUI
            User encontrado = myremoteObject.searchUser(nomeProcurar);

            // 3. Tratar o resultado
            if (encontrado != null) {
                // Se encontrou, pode mostrar os dados numa área de texto ou labels
                // Exemplo: txtAreaResultado.setText(encontrado.toString());
                JOptionPane.showMessageDialog(this, "Utilizador encontrado!\n" + encontrado.toString());

                // Aqui pode preencher outros campos da sua GUI com os dados de 'encontrado'
            } else {
                JOptionPane.showMessageDialog(this, "Utilizador não encontrado na rede.");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro na pesquisa: " + ex.getMessage());
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NomeUtenteActionPerformed

    public JTextField getTxtBalance1() {
        return txtBalance1;
    }

    public void setTxtBalance1(String Balance) {
        this.txtBalance1.setText(Balance);
    }

    public JTextField getTxtWalletAESKey1() {
        return txtWalletAESKey1;
    }

    public void setTxtWalletAESKey1(String AesKey) {
        this.txtWalletAESKey1.setText(AesKey);
    }

    public JTextField getTxtWalletPrivateKey1() {
        return txtWalletPrivateKey1;
    }

    public void setTxtWalletPrivateKey1(String PrivateKeys) {
        this.txtWalletPrivateKey1.setText(PrivateKeys);
    }

    public JTextField getTxtWalletPublicKey1() {
        return txtWalletPublicKey1;
    }

    public void setTxtWalletPublicKey1(String PublicKey) {
        this.txtWalletPublicKey1.setText(PublicKey);
    }

    public JTextArea getTxtWalletTransactions1() {
        return txtWalletTransactions1;
    }

    public void setTxtWalletTransactions1(String transicoes) {
        this.txtWalletTransactions1.setText(transicoes);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NodeP2PGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NodeP2PGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NodeP2PGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NodeP2PGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NodeP2PGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Medicamentos;
    private javax.swing.JTextField NomeUtente;
    private javax.swing.JTextField QuantidadeMed;
    private javax.swing.JButton btAddTransaction;
    private javax.swing.JButton btConnect;
    private javax.swing.JButton btStartMinig;
    private javax.swing.JButton btStartServer;
    private utils.FolderUtils folderUtils1;
    private javax.swing.JLabel imgMiner;
    private javax.swing.JLabel imgServerRunning;
    private javax.swing.JLabel imgWinner;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnNetwork;
    private javax.swing.JPanel pnServer;
    private javax.swing.JPanel pnTransaction;
    private javax.swing.JSpinner spZeros;
    private javax.swing.JTabbedPane tpMain;
    private javax.swing.JTextField txtBalance1;
    private javax.swing.JTextArea txtLstTransactions;
    private javax.swing.JTextArea txtMinerMessage;
    private javax.swing.JTextArea txtNetwork;
    private javax.swing.JTextField txtNodeAddress;
    private javax.swing.JTextField txtNonce;
    private javax.swing.JTextField txtServerListeningObjectName;
    private javax.swing.JTextField txtServerListeningPort;
    private javax.swing.JTextPane txtServerLog;
    private javax.swing.JTextField txtWalletAESKey1;
    private javax.swing.JTextField txtWalletPrivateKey1;
    private javax.swing.JTextField txtWalletPublicKey1;
    private javax.swing.JTextArea txtWalletTransactions1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onStart(String message) {
        imgServerRunning.setEnabled(true);
        btStartServer.setEnabled(false);
        GuiUtils.addText(txtServerLog, "Start server", message);
    }

    @Override
    public void onException(Exception e, String title) {
        JOptionPane.showMessageDialog(this, e.getMessage(), title, JOptionPane.WARNING_MESSAGE);
    }

    @Override
    public void onConect(String address) {
        try {
            List<RemoteNodeInterface> net = myremoteObject.getNetwork();
            String txt = "";
            for (RemoteNodeInterface iremoteP2P : net) {
                txt += iremoteP2P.getAdress() + "\n";
            }
            txtNetwork.setText(txt);
            tpMain.setSelectedComponent(pnNetwork);
            onTransaction("Syncronize to " + address);
        } catch (RemoteException ex) {
            onException(ex, "On conect");
            Logger.getLogger(NodeP2PGui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
@Override
public void onTransaction(String transaction) {
    SwingUtilities.invokeLater(() -> {
        try {
            tpMain.setSelectedComponent(pnTransaction);
            txtLstTransactions.setText("--- Histórico de Receitas ---\n\n");

            // Percorre todas as transações armazenadas no nó remoto
            for (String tr : myremoteObject.getTransactions()) {
                // Decodifica e converte para objeto
                byte[] data = Base64.getDecoder().decode(tr);
                SaudeTransaction obj = (SaudeTransaction) utils.Serializer.byteArrayToObject(data);
                
                // Adiciona ao TextArea usando o novo formato do toString()
                txtLstTransactions.append(obj.toString() + "\n------------------------------------------------\n");
            }
        } catch (Exception ex) {
            txtLstTransactions.append("Erro ao processar transação: " + ex.getMessage() + "\n");
        }
    });
}

    @Override
    public void onStartMining(String message, int dificulty) {
        SwingUtilities.invokeLater(() -> {
            imgMiner.setVisible(true);
            imgWinner.setVisible(false);
            txtMinerMessage.setText(message);
        });

    }

    @Override
    public void onStopMining(int nonce) {
        SwingUtilities.invokeLater(() -> {
            try {
                imgMiner.setVisible(false);
                btStartMinig.setEnabled(true);
                txtNonce.setText("" + nonce);
                txtMinerMessage.setText(myremoteObject.getHash());

            } catch (Exception ex) {
                System.getLogger(NodeP2PGui.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });

    }

    @Override
    public void onNonceFound(int nonce) {
        SwingUtilities.invokeLater(() -> {
            imgWinner.setVisible(true);
            try {
                myremoteObject.stopMining(nonce);
            } catch (RemoteException ex) {
                System.getLogger(NodeP2PGui.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

}
