/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 * Janela de Perfil do Utilizador.
 * <p>
 * Apresenta os detalhes da conta do utilizador atualmente autenticado, incluindo:
 * <ul>
 * <li><b>Dados Pessoais:</b> Nome, Nº Utente, Unidade de Saúde, etc.</li>
 * <li><b>Segurança:</b> Representação visual das chaves criptográficas (RSA/AES).</li>
 * </ul>
 * <p>
 * Esta janela é meramente informativa e não permite edição.
 * @author angelacsebastiao
 */
public class PerfilUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PerfilUser.class.getName());
    
    /** Referência ao objeto do utilizador cujos dados serão exibidos. */
    private SaudeCerteira.User user;
    
    /** Referência à janela principal para poder voltar atrás corretamente. */
    private javax.swing.JFrame mainGUI;

    /**
     * Construtor Principal.
     * @param user O objeto User contendo os dados a mostrar.
     * @param mainGUI A instância da janela principal (MainGUI) que chamou este perfil.
     */
   public PerfilUser(SaudeCerteira.User user, javax.swing.JFrame mainGUI) {
        initComponents();
        this.user = user;
        this.mainGUI = mainGUI;
        
        // Carrega os dados para a área de texto
        preencherDados(user);
        
        // Bloqueia a edição (modo leitura apenas)
        jTextArea1.setEditable(false);
        
        // Garante que ao fechar no 'X' não encerra toda a aplicação
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * Construtor padrão (sem argumentos).
     * Usado principalmente pelo editor visual ou testes rápidos.
     */
    public PerfilUser() {
        initComponents();
    }

    /**
     * Formata e exibe os dados do utilizador na JTextArea.
     * Converte as chaves binárias para Base64 para serem legíveis.
     * @param user O utilizador a apresentar.
     */
   private void preencherDados(SaudeCerteira.User user) {
    if (user != null) {
        StringBuilder info = new StringBuilder();
        
        // :::: SECÇÃO 1: Dados Pessoais ::::
        info.append("=== PERFIL DO UTILIZADOR ===\n");
        info.append("Nome: ").append(user.userName).append("\n");
        info.append("Data Nascimento: ").append(user.dataNascimento).append("\n");
        info.append("Nº Utente: ").append(user.numeroUtente).append("\n");
        info.append("Unidade de Saúde: ").append(user.getUnidadeSaude()).append("\n\n");
        
        // :::: SECÇÃO 2: Segurança ::::
        info.append("=== CREDENCIAIS CRIPTOGRÁFICAS ===\n");
        
        // Chave Pública (Identidade na Blockchain)
        String pubKeyBase64 = java.util.Base64.getEncoder().encodeToString(user.getPublicKey().getEncoded());
        info.append("Chave Pública (RSA):\n").append(pubKeyBase64).append("\n\n");
        
        // Chave AES (Segurança dos Dados)
        String aesKeyBase64 = java.util.Base64.getEncoder().encodeToString(user.aesKey.getEncoded());
        info.append("Chave AES:\n").append(aesKeyBase64).append("\n\n");
        
        // Chave Privada (Nunca mostrada por segurança)
        info.append("Chave Privada:\n******** (Protegida por Password)");

        // Renderizar na GUI
        jTextArea1.setText(info.toString());
        
    } else {
        // Tratamento de erro caso o login tenha falhado silenciosamente
        jTextArea1.setText("ERRO CRÍTICO: Nenhum utilizador logado encontrado.");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        voltarMainGUI = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(new java.awt.Color(0, 153, 153));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        voltarMainGUI.setBackground(new java.awt.Color(204, 255, 255));
        voltarMainGUI.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        voltarMainGUI.setText("Voltar");
        voltarMainGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMainGUIActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(voltarMainGUI))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(voltarMainGUI)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação do botão "Voltar".
     * <p>
     * Reabre a janela principal (MainGUI) que estava escondida e fecha esta janela de perfil.
     * @param evt O evento de clique.
     */
    private void voltarMainGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMainGUIActionPerformed
        if (mainGUI != null) {
            mainGUI.setVisible(true); // Restaura a MainGUI
            this.dispose(); // Destrói apenas a janela de Perfil
        }    
    }//GEN-LAST:event_voltarMainGUIActionPerformed

    /**
     * Ponto de entrada (Main) para testes isolados da janela.
     * @param args Argumentos da linha de comandos.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PerfilUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton voltarMainGUI;
    // End of variables declaration//GEN-END:variables

}